#ifndef EH_FLAGS_H
#define EH_FLAGS_H

#define EH_PARTICLE_STATIC 1
#define EH_PARTICLE_STATICMOVE 2
#define EH_PARTICLE_NOFORCE 4

#define DISTANCE_EPS_SQ 1e-4
#define GRADIENT_TENSOR_EPS 1e-2
#define LAPLACIAN_TENSOR_EPS 1e-1

#define STATIC_MASS 2.0

#endif
